version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: authenticationServiceDB
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Linistit123!
      POSTGRES_DB: authenticationServiceDB
    ports:
      - "9111:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "authenticationServiceDB"]
#  java:
#    image: openjdk:19
#    container_name: authenticationServiceDB
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./target:/app
#    command: ["java", "-jar", "/app/proiect-colectiv-backend-0.0.1-SNAPSHOT.jar"]
#    depends_on:
#      postgres:
#        condition: service_healthy
